name: Deployment

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Chec out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - id: auth
        uses: google-github-actions/auth@v2
        with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Build and push Docker image
        run: gcloud builds submit --tag REGION-docker.pkg.dev/notely-474009/notely-ar-repo/notely:v1 .
